dist: focal
arch: ppc64le

before_install:
  - |
    touch key
    echo "-----BEGIN RSA PRIVATE KEY-----" >> key
    echo "${BUILDER_KEY}" |  base64 -d -w 0 | cut -c 33- |  sed 's/.\{30\}$//g' | tr " " "\n" >> key
    echo "-----END RSA PRIVATE KEY-----" >> key
    chmod 0600 key

jobs:
  include:
    - name: release-check
      stage: release-check
      before_script:
        - |
          sudo apt-get update -y
          sudo apt-get install libxml2-utils -y
          LAST_VERSION=$(cat last_version)
      script:
        - |
          
          echo "Last version is ${LAST_VERSION}"
          
          chmod +x release-check.sh
          ./release-check.sh -l "${LAST_VERSION}" "actions/runner"
          
#           if [[ "$?" -ne 0 ]]; then
#             travis_terminate 1
#           fi
    
    - name: build-lxd-runner-image
      stage: build
      script:
        - |
          ls -lha
          echo "Copying necessary files to BUILDER_VM"
          
          scp -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \ 
            build-image.sh "ubuntu@${BUILDER_HOST}:/home/ubuntu/remote-build/files/"

          ssh -q -t -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@"${BUILDER_HOST}" \
            bash -s < setup-build-env.sh
