dist: focal
arch: ppc64le

before_install:
  - |
    touch key
    echo "-----BEGIN RSA PRIVATE KEY-----" >> key
    echo "${BUILDER_KEY}" |  base64 -d -w 0 | cut -c 33- |  sed 's/.\{30\}$//g' | tr " " "\n" >> key
    echo "-----END RSA PRIVATE KEY-----" >> key
    chmod 0600 key

before_script:
  - |
    sudo apt-get update -y
    sudo apt-get install libxml2-utils -y
    LAST_VERSION=$(cat last_version)

jobs:
  include:
    - name: release-check
      stage: release-check
      script:
        - |
          chmod +x release-check.sh
          ./release-check.sh -l "${LAST_VERSION}" "actions/runner"
          
          if [[ "$?" -ne 0 ]]; then
            travis_terminate
          fi
    
    - name: build-lxd-runner-image
      stage: build
      script:
        - |
          # chmod +x build-lxd-image.sh
          # ./build-lxd-image.sh
          
          chmod 0600 key
          ssh -i key ubuntu@"${BUILDER_HOST}"
          
          ls -lha
          ls /tmp
          
          exit
