dist: focal
arch: ppc64le

before_install:
  - |
    touch key
    echo "${BUILDER_KEY}" |  base64 -d -w 0 > key
    chmod 0600 key

jobs:
  include:
    - stage: release-check
      name: "Check actions/runner for new release"
      workspaces:
        create:
          name: release-check-file
          paths:
            - /tmp
      before_script:
        - |
          sudo apt-get update -y
          sudo apt-get install libxml2-utils jq -y
          LAST_VERSION=$(cat last_version)
      script:
        - |
          echo "Last version is ${LAST_VERSION}"
          chmod +x release-check.sh
          
          # TODO: if there are no new releases found, exit the Travis-CI build with success and not failure.
          ./release-check.sh -l $LAST_VERSION actions/runner || travis_terminate 1

    - &build-export
      stage: build-export
      name: "Build and save the LXD runner image"
      env: 
        - OS="22.04" 
        - DIST="Jammy"
      script:
        - |
          echo "Copying necessary files to BUILDER_VM"
          echo "Building for $OS"
          scp -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no build-image.sh "ubuntu@${BUILDER_HOST}:/home/ubuntu/remote-build/files/"

          ssh -q -t -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@"${BUILDER_HOST}" \
            bash -s < setup-build-env.sh $OS

    - <<: *build-export
      env: 
        - OS="20.04" 
        - DIST="Focal"
    
    - stage: update-last-version
      name: "Update last_version in gaplib"
      workspaces:
          use: release-check-file
      script:
        - |
          
          export NEW_VERSION=$(cat /tmp/new_version)
          echo "${NEW_VERSION}"
          
          # update last_version file in github
          bash .travis/update-last-version.sh "${NEW_VERSION}"
