dist: focal
arch: ppc64le

env:
    - BUILD_IMAGE=true

before_install:
  - |
    touch key
    echo "-----BEGIN RSA PRIVATE KEY-----" >> key
    echo "${BUILDER_KEY}" |  base64 -d -w 0 | cut -c 33- |  sed 's/.\{30\}$//g' | tr " " "\n" >> key
    echo "-----END RSA PRIVATE KEY-----" >> key
    chmod 0600 key

jobs:
  include:
    - name: release-check
      stage: release-check
      workspaces:
        create:
          name: release-check-file
          paths:
            - /tmp
      before_script:
        - |
          sudo apt-get update -y
          sudo apt-get install libxml2-utils -y
          LAST_VERSION=$(cat last_version)
      script:
        - |
          
          echo "Last version is ${LAST_VERSION}"
          
          chmod +x release-check.sh
          ./release-check.sh -l "${LAST_VERSION}" "actions/runner"
          BUILD_IMAGE=true
          
          if [[ "$?" -ne 0 ]]; then
            travis_terminate 1
          fi
    
    
    # - name: build-and-export-lxd-runner-image
    #   stage: build-export
    #   if: env(BUILD_IMAGE) = true
    #   script:
    #     - |
    #       echo "Copying necessary files to BUILDER_VM"
          
    #       scp -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no build-image.sh "ubuntu@${BUILDER_HOST}:/home/ubuntu/remote-build/files/"

    #       ssh -q -t -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@"${BUILDER_HOST}" \
    #         bash -s < setup-build-env.sh


    
    - name: update-last-version
      stage: update-last-version
      if: env(BUILD_IMAGE) = true
      workspaces:
          use: release-check
      script:
        - |

          if [[ ! -f /tmp/new_version ]]; then
              travis_terminate 1
          fi
          
          export NEW_VERSION=$(cat /tmp/new_version)
        
          # update last_version file in github
          bash .travis/update-last-version.sh "${NEW_VERSION}"
